global:
  scrape_interval: 15s # Har 15 second mein data check karega

scrape_configs:
  - job_name: 'watchtower-backend'
    static_configs:
      - targets: ['app:3000'] # Docker ke andar se aapke PC ka port 3000
    metrics_path: '/metrics'
